### ISSUE TITLE
Domain validation

### ISSUE THREAD

**Issue by LuckyF1sh** [trapped/gomaild2#8]
I tried to send message from "mail.ru" and then got an error in logs:

> level=info msg="Permanent failure" args=f415.i.mail.ru cmd=HELO id=SHsrTrYPXxsa reply="invalid domain" result=501

So:
gomaild2/smtp/structs/structs.go:

`RxDomain *regexp.Regexp = regexp.MustCompile("^([a-zA-Z0-9]{1}[a-zA-Z0-9_-]{1,62}){1}(\.[a-zA-Z0-9]{1}[a-zA-Z0-9_-]{1,62})+$")`

can not validate .i. (omg, what am I writing? XD) in domen

> f415.i.mail.ru

**Comment by trapped** [comment]
Try using this regex and tell me how it goes: "^([a-zA-Z0-9]{1}[a-zA-Z0-9_-]{0,62}){1}(\.[a-zA-Z0-9]{1}[a-zA-Z0-9_-]{0,62})+$"

**Comment by LuckyF1sh** [comment]
it goes fine now
